export default {
    translation: {
        fr: {
            // Ui / texts
            'add-deck': 'Ajouter un deck',
            'add': 'Ajouter',
            'deck-name': 'Nom du deck',
            'cards': 'Cartes',
            'no-deck-selected': 'Aucun deck sélectionné',
            'search': 'Recherche',
            'export-decks': 'Exporter les Decks',
            'export-deck': 'Exporter le deck sélectionné',
            'confirm-remove-deck': 'Êtes vous sur de vouloir supprimer ce deck ?',
            'no': 'Non',
            'yes': 'Oui',
            'import-default': 'Importer les decks par défaut',
            'Neutral': 'Neutre',
            'hero': 'Héro',
            'rarity': 'Rareté',
            'extension': 'Extension',
            'type': 'Type',
            'mechanics': 'Mécaniques',
            // CardType
            'Spell': 'Sort',
            'Minion': 'Serviteur',
            'Weapon': 'Arme',
            // Rarity
            'Free': 'Gratuit',
            'Common': 'Commune',
            'Rare': 'Rare',
            'Epic': 'Épique',
            'Legendary': 'Légendaire',
            // Card Set
            'Basic': 'Basique',
            'Classic': 'Classique',
            'Naxxramas': 'Naxxramas',
            'Goblins vs Gnomes': 'Gobelins et Gnomes',
            'Reward': 'Récompenses',
            'Blackrock Mountain': 'Le Mont Rochenoire',
            'The Grand Tournament': 'Le Grand Tournoi',
            'The League of Explorers': 'La Ligue des Explorateurs',
            // Mechanics
            'Battlecry': 'Cri de guerre',
            'Freeze': 'Gèle',
            'Aura': 'Aura',
            'Taunt': 'Provocation',
            'Charge': 'Charge',
            'Spellpower': 'Dégats des sorts',
            'Silence': 'Silence',
            'Overload': 'Surcharge',
            'Windfury': 'Furie des vents',
            'Stealth': 'Camouflage',
            'Divine Shield': 'Bouclier divin',
            'Deathrattle': 'Râle d\'agonie',
            'Secret': 'Secret',
            'Enrage': 'Accès de rage',
            'Combo': 'Combo',
            'Inspire': 'Exaltation'
        },
        en: {
            // Ui / texts
            'add-deck': 'Add Deck',
            'add': 'Add',
            'deck-name': 'Deck name',
            'cards': 'Cards',
            'no-deck-selected': 'No deck selected',
            'search': 'Search',
            'export-decks': 'Export Decks',
            'export-deck': 'Export current deck',
            'confirm-remove-deck': 'Are you sure you want to remove this deck ?',
            'no': 'No',
            'yes': 'Yes',
            'import-default': 'Import default decks',
            'Neutral': 'Neutral',
            'hero': 'Hero',
            'rarity': 'Rarity',
            'extension': 'Extension',
            'type': 'Type',
            'mechanics': 'Mechanics',
            // CardType
            'Spell': 'Spell',
            'Minion': 'Minion',
            'Weapon': 'Weapon',
            // Rarity
            'Free': 'Free',
            'Common': 'Common',
            'Rare': 'Rare',
            'Epic': 'Epic',
            'Legendary': 'Legendary',
            // Card Set
            'Basic': 'Basic',
            'Classic': 'Classic',
            'Naxxramas': 'Naxxramas',
            'Goblins vs Gnomes': 'Goblins vs Gnomes',
            'Reward': 'Reward',
            'Blackrock Mountain': 'Blackrock Mountain',
            'The Grand Tournament': 'The Grand Tournament',
            'The League of Explorers': 'The League of Explorers',
            // Mechanics
            'Battlecry': 'Battlecry',
            'Freeze': 'Freeze',
            'Aura': 'Aura',
            'Taunt': 'Taunt',
            'Charge': 'Charge',
            'Spellpower': 'SpellPower',
            'Silence': 'Silence',
            'Overload': 'Overload',
            'Windfury': 'Windfury',
            'Stealth': 'Stealth',
            'Divine Shield': 'Divine Shield',
            'Deathrattle': 'Deathrattle',
            'Secret': 'Secret',
            'Enrage': 'Enrage',
            'Combo': 'Combo',
            'Inspire': 'Inspire'
        }
    },
    dust: {
        'Free':      0,
        'Common':    40,
        'Rare':      100,
        'Epic':      400,
        'Legendary': 1600
    },
    rarity: {
        'Free':      'resources/gem_free.png',
        'Common':    'resources/gem_common.png',
        'Rare':      'resources/gem_rare.png',
        'Epic':      'resources/gem_epic.png',
        'Legendary': 'resources/gem_legendary.png'
    },
    cardType: [
        'Spell',
        'Minion',
        'Weapon'
    ],
    cardSet: {
        'Basic':                   'extension/Basic.png',
        'Classic':                 'extension/Classic.png',
        'Naxxramas':               'extension/Naxxramas.png',
        'Goblins vs Gnomes':       'extension/Goblins_vs_Gnomes.png',
        'Reward':                  'extension/Reward.png',
        'Blackrock Mountain':      'extension/Blackrock_Mountain.png',
        'The Grand Tournament':    'extension/The_Grand_Tournament.png',
        'The League of Explorers': 'extension/The_League_of_Explorers.png'
    },
    mechanics: [
        'Battlecry',
        'Freeze',
        'Aura',
        'Taunt',
        'Charge',
        'Spellpower',
        'Silence',
        'Overload',
        'Windfury',
        'Stealth',
        'Divine Shield',
        'Deathrattle',
        'Secret',
        'Enrage',
        'Combo',
        'Inspire'
    ]
};
